# Generated by Django 5.1.1 on 2024-10-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_courier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
