# Generated by Django 5.1.1 on 2024-09-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='abbreviation',
            field=models.CharField(default='NP', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default={'1': 4, '2': 3}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
