"""удаляем price (integer)

Revision ID: 09d0fa5d4d12
Revises: e2954907619f
Create Date: 2024-10-07 15:25:12.407158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d0fa5d4d12'
down_revision: Union[str, None] = 'e2954907619f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_price')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.INTEGER(), nullable=True))
    op.add_column('orders', sa.Column('total_price', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
