"""добавляем дату-время подтверждения заказа

Revision ID: 77ba38986234
Revises: 81ad84d75366
Create Date: 2024-10-07 16:18:56.325410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ba38986234'
down_revision: Union[str, None] = '81ad84d75366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'confirmed_at')
    # ### end Alembic commands ###
