"""добавляем price (decimal)

Revision ID: 81ad84d75366
Revises: 09d0fa5d4d12
Create Date: 2024-10-07 15:27:11.456745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ad84d75366'
down_revision: Union[str, None] = '09d0fa5d4d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    op.drop_column('orders', 'total_price')
    # ### end Alembic commands ###
