"""1

Revision ID: b3034f77c5b0
Revises: 80437c60bb11
Create Date: 2024-10-01 12:42:01.934321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3034f77c5b0'
down_revision: Union[str, None] = '80437c60bb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_city_id', table_name='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_city_id', 'orders', ['city_id'], unique=False)
    # ### end Alembic commands ###
