"""добавление полей в order и profile

Revision ID: c7cb8bf0232a
Revises: 87c688e6863b
Create Date: 2024-10-06 18:36:02.849331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7cb8bf0232a'
down_revision: Union[str, None] = '87c688e6863b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_delivered_time', sa.DateTime(), nullable=True))
    op.add_column('profiles', sa.Column('is_manager', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('is_courier', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_courier')
    op.drop_column('profiles', 'is_manager')
    op.drop_column('orders', 'is_delivered_time')
    # ### end Alembic commands ###
