"""добавление total_price в order

Revision ID: e2954907619f
Revises: c7cb8bf0232a
Create Date: 2024-10-07 14:44:55.812573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2954907619f'
down_revision: Union[str, None] = 'c7cb8bf0232a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_price')
    # ### end Alembic commands ###
